---
version: 2
jobs:
  test:
    docker:
      - image: node:latest
    working_directory: ~/leif
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run leif
          command: |
            yarn posttest
            yarn prepack
            ./bin/run run test/leif.yml
workflows:
  version: 2
  leif:
    jobs:
      - test
